### ISSUE TITLE
Support for Swift

### ISSUE THREAD

**Issue by araxara** [AgileBits/onepassword-app-extension#101]
I am planning to make all my new iOS apps in Swift and although I can have a mixed project (Obj-C & Swift), it would be nice to have everything in Swift. At least there should be some Swift Demos.

**Comment by ghecho** [comment]
Hi, I've just submitted a PR for this (Extension and basic Demo), hope it helps. 😃

**Comment by radazzouz** [comment]
Thanks so much @ghecho :+1: 

I just commented on PR #192.

Cheers!

**Comment by radazzouz** [comment]
PR #192 was closed, therefore referencing PR #194 here.

**Comment by ghecho** [comment]
Yes. I closed the first PR because I couldn't find how to change the branch within the PR so I closed that and opened a new one. If there's a way of editing the PR branch I'd like to know.

**Comment by radazzouz** [comment]
Hi @ghecho,

I just googled and I found this: https://github.com/isaacs/github/issues/18

By the looks of it, changing the destination branch for an already opened PR is not yet supported. So I guess that what you did (closing and re-opening) was the right thing to do.

Cheers!

**Comment by ghecho** [comment]
Cool. Glad to know. 

Cheers!

**Comment by radazzouz** [comment]
Hey everyone,

I just finished the two demo apps (**ACME** and **ACME Browser**) in Swift. Please take a look at the [new/swift-demo-apps](https://github.com/AgileBits/onepassword-app-extension/tree/new/swift-demo-apps/Demos) branch.

Feel free to PR improvement to that branch :smile: 

Thanks!

**Comment by ghecho** [comment]
I just submitted a PR (tiny by the way, just a cosmetic layout issue on the iPhone)

**Comment by radazzouz** [comment]
Thanks @ghecho! The PR is now merged :+1:

**Comment by ghecho** [comment]
:+1:

**Comment by ghecho** [comment]
In WWDC 2015 Apple announced availability tools for swift like: 
```swift
if #available(iOS 8.0, *)
{
...
}
```

That allows (as far as I can see) the library to be rewritten in Swift completely for iOS 9. :wink:

**Comment by radazzouz** [comment]
Hi @ghecho,

Thanks for the suggestion :wink: 

It's easier to add Objective-C code to Swift projects than Swift code to Objective-C projects. That's why we'd like to keep our API in Objective-C for the time being.

Please make sure that you take a look at our Swift demo apps. They are currently available in separate branches:

**Swift 1.2**

[new/swift-demo-apps](https://github.com/AgileBits/onepassword-app-extension/tree/new/swift-demo-apps)

**Swift 2.0 (requires Xcode 7)**

[swift2.0](https://github.com/AgileBits/onepassword-app-extension/tree/swift2.0)

Enjoy your weekend!

**Comment by ghecho** [comment]
Hi @radazzouz ,

Cool, I didn't checked until now those branches, I understand your logic, It's just that I'm porting many of my projects to Swift and I didn't see legacy support (as in Objective-C support) as a priority but giving that a second thought and since 1Password is widely used your approach makes total sense.

Have a nice week!

**Comment by radazzouz** [comment]
Thanks @ghecho :smile:

**Comment by radazzouz** [comment]
Resolved by PR #257.
