### ISSUE TITLE
Need ability to to provide an alias for the “username” field when creating a new login

### ISSUE THREAD

**Issue by irace** [agilebits/onepassword-app-extension#118]
I have a sign-up screen with the following three fields on it:
- Email address
- Password
- Username

I'm considering adding integration with the 1Password extension, but the UX is confusing because the extension uses “username” to refer to the field where the user should enter their email address, while “username” means something different in the application itself.

It'd be great to be able to provide an temporary, alternative field name to be used in the extension in place of “username,” to avoid having this overloaded term confuse the user.

The interface could be as simple as something like:

``` objc
NSDictionary *parameters = @{
    AppExtensionUsernameTemporaryFieldNameKey: @"email address"
    AppExtensionUsernameKey: @"bryan@domain.com"
    AppExtensionPasswordKey: @"qwerty"
    AppExtensionFieldsKey: @{
        @"username": @"bryanirace"
    }
};
```

Thank you!

**Comment by soffes** [comment]
For what it's worth, I'd also really like this functionality. For our service, you can sign in with your username or email (and a password). When signing up, a username, email, and password is required. Due to this restriction in the 1Password extension, I don't think we'll be able to use it in our sign in form.

If we could just change the label from "Enter your username or email address" in the 1Password UI to one or the other, I could use it fill that field and the password field after the extension completes and have the user manually fill in the last field in my UI before submitting the form.

Have you given any more consideration to this issue?

Thanks!

**Comment by radazzouz** [comment]
Hi @soffes,

Thanks for the followup! :+1:

I am standing by this [previous comment](https://github.com/AgileBits/onepassword-app-extension/issues/118#issuecomment-58955510) of mine from almost two years ago: Allowing developers to change the `username` field's title/designation can lead to huge compatibility (to name the most obvious) issues, affecting all platforms (iOS, Mac, Windows, Android, our Brain and our JavaScript Browser extension). Hence, I am labeling this issue as `won't do`.

> If we could just change the label from "Enter your username or email address" in the 1Password UI to one or the other, I could use it fill that field and the password field after the extension completes and have the user manually fill in the last field in my UI before submitting the form.

I am not 100% certain if we updated the username field's placeholder string since this issue was first opened, but now it shows "Username or Email". And from 1Password's point of view, the username field can be either a `username` or an `email address`. 1Password and its extensions (on all platforms) "know" how to fill usernames and passwords. 

Also, we do not want to expose APIs that allow developers to change critical fields. Thanks for understanding.

If there's anything else I can assist with, please let me know!

Cheers!

**Comment by irace** [comment]
Again, Sam isn’t requesting access to actually _change_ anything, he just wants control over the way that the user is prompted to create their 1Password entry. Since this flow is happening within the context of his app, he needs the ability to (**temporarily**) tweak the 1Password extension’s copy in order to stay consistent with his own copy.

I’m really surprised this is so controversial.

**Comment by soffes** [comment]
@irace I solved this by with the following:

```swift
// Get username or email from 1Password and focus the remaining field
if let username = loginDictionary?[AppExtensionUsernameKey] as? String {
	if username.containsString("@") {
		emailTextField.text = username
		usernameTextField.becomeFirstResponder()
	} else {
		usernameTextField.text = username
		emailTextField.becomeFirstResponder()
	}
}

// Get password from 1Password
if let password = loginDictionary?[AppExtensionPasswordKey] as? String {
	passwordTextField.text = password
}
```

I think this is an acceptable workaround for the **won't do**.

**Comment by ibsh** [comment]
I agree that it would be very helpful to change the visual prompt from "Username or email" to just "Email" or an arbitrary string when using the app extension.
