### ISSUE TITLE
Password with `'` in it will not fill

### ISSUE THREAD

**Issue by spenrose** [AgileBits/onepassword-app-extension#156]
This is the error I get:

```
015-01-21 01:34:12.522 PrettyOK[8452:3245132] completed request - items: (
    "<NSExtensionItem: 0x17020aa40> - userInfo: {\n    NSExtensionItemAttachmentsKey =     (\n        \"<NSItemProvider: 0x170440f00> {types = (\\n    \\\"com.apple.property-list\\\"\\n)}\"\n    );\n}"
)
2015-01-21 01:34:13.110 PrettyOK[8452:3248752] LaunchServices: invalidationHandler called
2015-01-21 01:34:17.358 PrettyOK[8452:3245132] Cannot executeFillScript, evaluateJavaScript failed: Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo=0x170461d80 {NSLocalizedDescription=A JavaScript exception occurred}
Failed to fill login in webview: Error Domain=OnePasswordExtension Code=5 "Failed to fill web page because script could not be evaluated" UserInfo=0x170276bc0 {NSLocalizedDescription=Failed to fill web page because script could not be evaluated}
error Optional([NSLocalizedDescription: Failed to fill web page because script could not be evaluated])
```

If I change the password so it doesn't contain a `'` character it fills fine.

**Comment by radazzouz** [comment]
Hi @spenrose,

Thanks for taking the time to write to us and for reporting this issue :+1:

This issue along with other filling issues have been fixed in 1Password for iOS `5.3` betas. To properly test the fix, you also need to use the **1Password App Extension API** from master and not the stable `1.1.0` version.

If you are not already using our TestFlight betas and wish to test the fix, please give us a shout at [support+appex@agilebits.com](support+appex@agilebits.com).

I will close this issue for now, please re-open if you're still encountering issues after updating to the 5.3 betas.

Cheers!
