### ISSUE TITLE
Consider adding an API for updating usernames.

### ISSUE THREAD

**Issue by davepeck** [AgileBits/onepassword-app-extension#173]
There doesn't appear to be a clean way to update 1Password when a `username` changes but other details stay the same. 

(It isn't quite equivalent to simply saving a new login; a typical `username` update form requests the new username but the current password.)

**Comment by radazzouz** [comment]
Hello Dave,

Thanks for taking the time to write in :+1:

In fact, we had an API for changing the username in the early beta versions the App Extension API. We did it within `-[OnePasswordExtension changePasswordForLoginForURLString:]` and it has proven to be a PITA, so we decided to offer it longer and we removed it in PR #79.

The main issue is that 1Password is not designed to validate usernames received from third party apps. Which means that the host app could validate that the username was unique and accepted by the back end prior to calling the 1Password Extension. But there is no way to prevent the user from editing the username once again in the extension.

Here’s a very common scenario:

1. The developer ensures that the user enters a valid username before allowing the user to invoke the 1Password extension.
2. The user calls the 1Password extension and modifies the username sent by the host app and taps on "Done".
3. The modified username is saved in 1Password and sent back to the host app.
4. The username change fails because the username is already taken or contains wrong characters.

I hope that this helps :smiley:

Cheers!

**Comment by davepeck** [comment]
Hi @radazzouz -- thanks, and good to know the history here!

Since iOS extensions are so limited in scope, it seems like it would be quite hard (impossible?) for the 1Password extension to participate meaningfully in _any_ kind of validation. To do so would require back-and-forth between the extension and the invoking app that doesn't seem possible with iOS today.

Hrm. I suppose one way the 1Password extension could _cheaply_ help with validation would be to allow the calling app to specify fields that should be read-only. This would allow the app to pre-verify whatever content it likes, populate the call to 1Password, and be certain that the verified content will not get modified along the way. 

I don't know if you've considered something like this, or whether there are perhaps usability or even security implications for the approach, but at first blush it would seem to be helpful...

Cheers,
Dave

**Comment by radazzouz** [comment]
Hi @davepeck,

Thanks so much for getting back to us and for your "first blush" :+1:

Indeed, we've thought about disabling editing for the username field, but as you already said, this is a usability issue: The user may be confused why certain fields cannot be edited while others can.

We are definitely opened for ideas on a method that would allow changing more than the Login's password. We would also really love if you, or someone else, could come up with an awesome second or third "blush” :smiley:

That’s why I am leaving this issue opened for now. So that it is visible to everyone.

Best,

**Comment by radazzouz** [comment]
This issue is no longer `under consideration`. Closing it for now.
