### ISSUE TITLE
Support for looking up credentials for multiple sites

### ISSUE THREAD

**Issue by maxdisney** [AgileBits/onepassword-app-extension#195]
We have a shared credential system, so you can have the same login for parentsite.com and childsitewithadifferentdomain.com; some users only have it saved for one. Have you guys considered the ability to look up any credentials for a set of domains?

**Comment by radazzouz** [comment]
Hi @maxdisney,

Thanks for taking the time to write to us :+1:

Searching Logins for multiple domains has been requested several times in the past (see #131 and all the related issues). So we implemented the **Show all Logins** feature in the recently release 1Password 5.3 for iOS. 

![](https://www.evernote.com/shard/s340/sh/d5cffb32-de87-49e1-80a4-95d07bf61f23/2bcc938b22ca0ad67da2b805495b0146/deep/0/Screenshot-2015-04-06,-10-01-AM.png)

So here's how the **Show all Logins** feature works in 1Password 5.3:

* Your app will still use for a single and unique URL string. Let's say ** parentsite.com**
* If now matching Login is found in the user's database the **Show all Logins** "button" will show up.
* The user taps on it.
* All logins will now be shown.
* The user can scroll or search through the entire list for the desired Login, in this case for ** childsitewithadifferentdomain.com**

Hope that this helps :smile: 

I will close this issue for now as a duplicate. Please feel free to comment on #131 in order to keep all the comments in one place.

Cheers!
