### ISSUE TITLE
Cut 1.2.1 release?

### ISSUE THREAD

**Issue by jflinter** [AgileBits/onepassword-app-extension#228]
Version 1.2, the current latest release, builds with warnings when using Cocoapods with frameworks. This has thankfully been fixed as of cead0af2e5b35f649edd7d87b3180ec3d095d18d, but there hasn't been a new release cut since then. Mind cutting a new point release so I can stop pointing at HEAD in order to get a clean build?

**Comment by radazzouz** [comment]
Hi @jflinter,

Thanks for taking the time to write to us :thumbsup:

The branch `master` is still in development, it contains changes that aren't fully supported in the current version of **1Password for iOS** from the App Store. This is one of the reasons why we cannot release an **App Extension API** update off of it in its current state, nor can we do it from the commit that you mentioned since that commit occurred in the middle of the development cycle.

The good news is that, we do plan on pushing a new **CocoaPods** update for the **1Password App Extension API** in the near future.

In the meantime, as a temporary workaround, we suggest that you update your pod file either to checkout the commit that you mentioned or master, if you’re feeling adventurous :wink:

**Here's how to update your pod file to:**

**Pull from master**

```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'master'
```

**Pull specific commit**
```
pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :commit => '6980efe9ba08a8a7e873d6321a44ad893052e20b'
```

Hope that this helps :smiley:

Have an amazing weekend!

**Comment by jflinter** [comment]
Hi there,
I think you're mistaken - almost nothing has changed between the 1.2 tag and cead0af2e5b35f649edd7d87b3180ec3d095d18d, so it should be totally safe to tag that commit. You can visualize this at https://github.com/AgileBits/onepassword-app-extension/compare/1.2...cead0af2e5b35f649edd7d87b3180ec3d095d18d - besides the fix to `1Password.xcassets` that I want, the only other change involves renaming a variable in a way that doesn't affect anything else.
I'm already pointing my `Podfile` at the commit in question; I just think it's bad form to require your users to do that in order to get your library to build without any warnings.

**Comment by radazzouz** [comment]
Hi @jflinter,

Thanks for getting back to us and for sharing your thoughts.

I am sorry about the misunderstanding, we do not _require_ developers to checkout specific commits or branches. It was simply a _suggestion_ as a temporary workaround (see my previous comment). Please feel free to checkout any commit or branch that suits your needs. You could also fork this repo and make all the necessary changes that your project requires.

You are right about the commit in question and I stand corrected: The commit occurred at the beginning of the development cycle and not in the middle. So technically, we could just simply tag that commit with `1.2.1`. However, note that an update requires more than just a tag: extensive testing, updating the Podspec, the README, etc.

As I said in my initial comment, right now our focus is on the major stable release planned for the near future which also addresses the warnings you mentioned.

Please stay tuned! :smiley:

Best,

**Comment by jflinter** [comment]
I think you're getting hung up on what I meant by "require" - I understood your suggestion, and as I mentioned, I've already been pointing my `Podfile` at that specific commit.

The reality is, though, that if you want to use the 1Password app extension, and you want the library to build without warnings, you actually are _required_ to do this, as there is literally no other way to get a clean build of your SDK.

Regarding your suggestion that this requires too much work - this is literally a 1-line change to your `podspec`. It doesn't require "extensive testing", you don't have to update your `README`, there is no "etc" here. You could have done it in the time it's taken me to write this message. Here, I'll save you the trouble:

```bash
# create your tag
git checkout master
git tag -a 1.2.1 cead0af2e5b35f649edd7d87b3180ec3d095d18d -m "1.2"
git push --tags origin master

# update the podspec by merging #229

# publish 1.2.1 to cocoapods
pod trunk push
```

I know this seems pedantic, but right now your SDK is generating the only warning in my project, and it's really annoying, both to me and for others that want to use this library.

**Comment by radazzouz** [comment]
Hello @jflinter,

Thank you for taking the time to reply again and to submit PR #229.

As I mentioned in my previous comments, we are not ready yet to publish a new release of the **App Extension API** at this time, but we will be very soon.

> I know this seems pedantic, but right now your SDK is generating the only warning in my project, and it's really annoying, both to me and for others that want to use this library.

I do feel your frustration and I would really appreciate your patience in this matter. That is exactly why we recommend the temporary workaround or the DIY approach (fork) to get rid of the warning in your project.

I will be closing PR #229 for now.

Thank you!

**Comment by klaaspieter** [comment]
You made it pretty clear that you choose not to change this. Regardless of our opinions, as maintainers, that is your right.

However I have to agree @jflinter that the reasons offered are not convincing. It _is_ a simple change that I'm sure many of your users would appreciate.

I hope the status of this issue is not indicative of how future, potentially more impactful, issues are handled.
