### ISSUE TITLE
Allow UIPopoverControllerDelegate to be passed in to extension

### ISSUE THREAD

**Issue by rtl-0x0** [AgileBits/onepassword-app-extension#243]
When using the 1Password extension on the iPad it appears in a popover (Note that your ACME app is of such dimensions that it displays the extension in an action sheet, but this is not standard e.g. see the images in https://github.com/artsy/eigen/pull/435 which is referenced by #147). 

In order to control the location of the popup, when the device is rotated for example, Apple provides a UIPopoverControllerDelegate and in particular popoverController:willRepositionPopoverToRect:inView

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPopoverControllerDelegate_protocol/#//apple_ref/occ/intfm/UIPopoverControllerDelegate/popoverController:willRepositionPopoverToRect:inView:

Having the app pass in a UIPopoverControllerDelegate to the 1Password extension enables the app to very precisely control the location of the 1Password popup. 

Note that this approach has been used in a real app - findLoginIn1PasswordWithURLString() and all the callers were extended to take the delegate as a param e.g. forPopoverDelegate:(nullable id)popoverControllerDelegate which was used as follows:

    if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
        //iPhone, present activity view controller as is
        [forViewController presentViewController:activityViewController animated:YES completion:nil];
    }
    else
    {
        //iPad, present the view controller inside a popover
        if (![self.activityPopover isPopoverVisible]) {
            NSAssert(popoverControllerDelegate != nil, @"popoverControllerDelegate must not be nil");
            self.activityPopover = [[UIPopoverController alloc] initWithContentViewController:activityViewController];
            [self.activityPopover presentPopoverFromRect:[sender frame] inView:webView permittedArrowDirections:UIPopoverArrowDirectionAny animated:YES];
            [self.activityPopover setDelegate:popoverControllerDelegate];
        }
        else
        {
            //Dismiss if the button is tapped while pop over is visible
            [self.activityPopover dismissPopoverAnimated:YES];
        }
    }

iOS helpfully then calls back into the controlling app when it is about to reposition the popup and the location rectangle can be modified to suit. This is especially useful when the underlying app is a hybrid and there are no actual UIViews to attach the popup to (via the existing frame or rect param).

Obviously this is all a little hand-wavy without real code and/or a pull request, but the changes are quite extensive since the delegate needs to be passed through from the top level call and there are potentially other approaches - this starts the ball rolling at least.

**Comment by radazzouz** [comment]
Hi @rtl-0x0,

Thanks so much for taking the time to write in :+1:

I see that you are using one of our the web filling capabilities since you mentioned the `findLoginIn1PasswordWithURLString:` method. Note that this method is called in `fillItemIntoWebView:` which has a sender parameter. If the sender is an instance of ` UIBarButtonItem` or `UIView` the share sheet popover should show up properly on iPad, see the code in: [`activityViewControllerForItem:`](https://github.com/AgileBits/onepassword-app-extension/blob/master/OnePasswordExtension.m#L526).

Also, [`UIPopoverController`](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIPopoverController_class/index.html#//apple_ref/doc/uid/TP40009306-CH1-SW11) has been deprecated in iOS 9, so it doesn’t seem like a good idea too move towards this. Apple themselves recommend to use  the UIViewController presentations.

```
NS_CLASS_DEPRECATED_IOS(3_2, 9_0, "UIPopoverController is deprecated. Popovers are now implemented as UIViewController presentations. Use a modal presentation style of UIModalPresentationPopover and UIPopoverPresentationController.")
@interface UIPopoverController : NSObject <UIAppearanceContainer> {}
```

So here are our suggestions:

* Use a non nil and valid sender in `fillItemIntoWebView:`.

     ```objective-c
      	[[OnePasswordExtension sharedExtension] fillItemIntoWebView:self.webView forViewController:self sender:sender showOnlyLogins:NO completion:^(BOOL success, NSError *error) {
		if (!success) {
			NSLog(@"Failed to fill into webview: <%@>", error);
		}
	}];
     ```

* Implement web view filling in your app using your own `UIActivityViewController`. For more information, documentation and sample apps, please take a look at our [Adding the 1Password extension to a custom UIActivityViewController gist](https://gist.github.com/radazzouz/1f32eca216b1963dfc78).

Please let me know if you have any questions. For the time being I will close this issue as `invalid`, but please feel free to reopen it if I am missing something.

Cheers!
