### ISSUE TITLE
google login 

### ISSUE THREAD

**Issue by arunmahask** [AgileBits/onepassword-app-extension#250]
i am having the following issue and the black color screen displaying on screen there is no further more process, while showing the sign in screen for google sing in process, by the below line

 [self presentViewController:[self createAuthController] animated:YES completion:nil];

DiskCookieStorage changing policy from 2 to 0, cookie file:
DiskCookieStorage changing policy from 0 to 2, cookie file:

**Comment by radazzouz** [comment]
Hi @arunmahask,

Thanks for taking the time to write in :+1:

I am not sure I have enough information about the problem that you’re seeing there. Am I right to assume that your issue is related to *gtm-oauth2*? If so, similar issues (#85 and #142) have previously been opened a while ago. The solution was to update the Google libraries which had different cookie handling.

For more details, please refer to @akac's Awesome reply [here](https://github.com/AgileBits/onepassword-app-extension/issues/85#issuecomment-53804807).

Hope that this helps :wink:

Cheers!

**Comment by radazzouz** [comment]
@arunmahask, did the instructions from my previous comment help?

I am assuming that "no news, is good news", so I am closing this issue.

Best,
