### ISSUE TITLE
-canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "(null)"

### ISSUE THREAD

**Issue by maximedegreve** [AgileBits/onepassword-app-extension#255]
![screen shot 2015-09-03 at 14 20 24](https://cloud.githubusercontent.com/assets/980622/9659202/0151f884-5247-11e5-9124-399741e2c0f3.png)

and used this code to check if available:
    
    if([[OnePasswordExtension sharedExtension] isAppExtensionAvailable]){
        self.btn1Password.hidden = NO;
       // DO OTHER STUFF
        [self.view layoutIfNeeded];
    } else {
        self.btn1Password.hidden = YES;
    }

I'm missing something?

iPhone 6, iOS9, OnePassword is not installed

**Comment by radazzouz** [comment]
Hi @maximedegreve,

You need to have 1Password installed in order for `[[OnePasswordExtension sharedExtension] isAppExtensionAvailable]` to return `YES`. It is normal for `canOpenURL:` to return `NO` if 1Password is not installed.

I am closing this issue as `invalid`, but please feel free to re-open it if I missed something.

Cheers!

**Comment by maximedegreve** [comment]
Sorry if I wasn't clear with "OnePassword is not installed", I meant the app isn't installed on the phone. The extension is installed of course...

**Comment by radazzouz** [comment]
The 1Password extension is bundled inside the main 1Password app. You cannot have the 1Password extension installed without having 1Password installed.

Please install 1Password on your iPhone and let me know if it works.

Best,

**Comment by maximedegreve** [comment]
god I'm making a mess here,

onepassword-app-extension is installed in the iPhone project and [[OnePasswordExtension sharedExtension] isAppExtensionAvailable] is throwing an error saying: -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "(null)"

So this is normal?

**Comment by radazzouz** [comment]
Hello again, @maximedegreve,

Thanks for getting back to me and thank you for your patience :+1:

Yes, this is normal. `[[OnePasswordExtension sharedExtension] isAppExtensionAvailable]` will return `NO` if 1Password from the App Store is not installed on the same device as your app.

There are two important factors that need to be present in this setup:

* An app using the 1Password App Extension API (onepassword-app-extension) from this repo. It could be your app or one of our sample apps: ACME or ACME Browser.

* 1Password for iOS from the [App Store](https://itunes.apple.com/ca/app/1password-password-manager/id568903335?mt=8).

Hope that this helps :smiley:

**Comment by maximedegreve** [comment]
Cheers thank you ;-)

**Comment by wayx** [comment]
@radazzouz 
Hello, can you clarify please, why extension prints error about `canOpenURL failed` in console if 1password isn't installed? It's just like log message for developing purposes?
Thanks

**Comment by radazzouz** [comment]
Hi @wayx,

This is logged by `- [UIApplication canOpenURL:]`, because your app is trying to open a URL scheme (`org-appextension-feature-password-management://`) that can not be opened by any other app installed on your device. 1Password responds to the above mentioned URL scheme, so `- [UIApplication canOpenURL:]` will return `YES`.

![](https://www.evernote.com/l/AVS_Cm4rQzxCsID3q5U70vhKXzJOKcV0fwkB/image.png)

Note that the error is `nil` (`error: "(null)"`) and that `- [UIApplication canOpenURL:] does not offer error handling. IMO, the method should have been `- [UIApplication canOpenURL:error:]`. May be worth filing a rdar :wink:

Hope that this helps.

Cheers!

**Comment by wayx** [comment]
I see now, maybe worth )
Thanks!

**Comment by radazzouz** [comment]
You're welcome :smiley:

**Comment by pvinis** [comment]
@radazzouz i am getting something similar but weirder. i have two phones here, none of them has 1p installed. one gives me `error: "This app is not allowed to query for scheme org-appextension-feature-password-management"`, and the other one `canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"`.
the one with `error -10814` also does not return yes or no. it returns null.

**Comment by gks** [comment]
Hi @pvinis 

I believe our README outlines the reason this is happening, this is the relevant bit:

```
Important: isAppExtensionAvailable uses - [UIApplication canOpenURL:]. Since iOS 9 it is recommended that you add the custom URL scheme, org-appextension-feature-password-management, in your target's info.plist as follows:
```
See the rest [here](https://github.com/agilebits/onepassword-app-extension#use-case-1-native-app-login)

But you basically have to add any URL schemes you're going to query to your Info.plist and that'll take care of things. In this case add the org-appextension-feature-password-management scheme. 

Please let me know if you encounter any other trouble.

**Comment by pvinis** [comment]
i do that that. thats the weird thing. i tested on three phones. the one with 1p installed, returns yes and works. one without 1p installed, gives no, and the third phone gives null and canOpenUrl gives this error and doesnt return, hence the null.

**Comment by gks** [comment]
Hi @pvinis I've found some more documentation on this, hopefully these are useful for you:

[Stack overflow](http://stackoverflow.com/questions/32870393/canopenurl-this-app-is-not-allowed-to-query-for-scheme-instragram)

This one is notable because it explains that 
1. You need to specify the scheme only, so double check that you only have `org-appextension-feature-password-management` only and not :// or something else in there.
2. Make sure you spelled it correctly :) As that poor soul in the link had issues with

[UseYourLoaf](https://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/) has some details on this as well, might be worth giving that a read.

If you continue to have issues here could you please write in at support+appex@agilebits.com with a sample project that shows the issue?
