### ISSUE TITLE
Feature request: More information in the search results

### ISSUE THREAD

**Issue by rahaug** [AgileBits/onepassword-app-extension#273]
Feature request
----
I like to name my items like "Gmail" and place it in a project folder. When I search for Gmail in one of the browser extensions I cannot tell the items apart from each other, because folders, tags or usernames does not show.

I wish that the results contained more information. What if you included the username after the item name? Gmail (email@gmail.com).

I would also love the possibility to search for a folder and get all items listed.

It is not possible to search for email@gmail.com either, which makes it difficult to use the extension when I organize my items as I do. I know I can name my items differently, but I don't want to change my organization scheme.

**Comment by radazzouz** [comment]
Hi @rehang,

Thanks for taking the time to write in :+1:

When you call the **1Password App Extension** for iOS in Safari or in third party browsers, you will see all matching Logins (for "google.com" in your case), Credit Cards and Identities. If you have enough items (more than 9) the search field will show up.  Item details such as title, username, URL, custom fields, tags, etc. are searchable. Note that folders are not searchable.

So in your case, where you have multiple items named “Gmail” there are a couple of ways to distinguish them:

* See the username bellow the title.

![](https://www.evernote.com/l/AVTWMeIGPphMbJdelKJwXZG4_uoOYtwmCDoB/image.png)

* Tap on the `(i)` button to see the item detail view.

![](https://www.evernote.com/l/AVSD_sSAFeZOWrOuyqEaOrW3Y3sauRg_OdYB/image.png)

Hope that this helps :wink:

Since this is not an **App Extension API** issue, I am labeling this issue with `question` and `invalid` and closing it. For 1Password related issues, questions or feature requests please join our [discussions forums](https://discussions.agilebits.com). Our team will be delighted to assist you :smiley:

Have an amazing weekend!

Cheers!

**Comment by rahaug** [comment]
Thank you for your prompt reply @radazzouz.

Just to clearify, my question is based on the browser extensions (Chrome and Safari, Mac). I'm sorry if I posted this the wrong place. I thought "1password App Extension" included the broswer extensions.

As you see, when you have tens of database credentials named MySQL or other items named the same this can be tiresome.
<img width="309" alt="Screenshot of browser extension" src="https://cloud.githubusercontent.com/assets/306927/10710065/01c8d9ea-7a47-11e5-836a-1b50dca42923.png">

I want to move from lastpass but this might be a deal breaker for me and I dont want to spend time renaming all my items after an import.

**Comment by radazzouz** [comment]
Hi @rahaug,

Thanks for getting back to me and for clarifying matters :+1: 

This repository is dedicated the the App Extension API. 1Password mini and the browser extensions have different code bases. So I just filed an improvement (OPM-3354) in our internal bug tracker for 1Password for Mac,

The only workaround at this time is to manually rename your items. 

Enjoy your Saturday!

Best,
