### ISSUE TITLE
use_frameworks! broken with CocoaPods 0.39.0

### ISSUE THREAD

**Issue by obuseme** [AgileBits/onepassword-app-extension#276]
I'm still having problems with using `use_frameworks!` in conjunction with OnePasswordExtension 1.6.3 installed via CocoaPods 0.39.0.

I can reliably reproduce this by:
Create new Swift project
Add Objective-C file, and create bridging header
Add podfile with simply `use_frameworks!` and `pod '1PasswordExtension', '~> 1.6.3'`
pod install
Open workspace
Any reference to `OnePasswordExtension` from Swift results with a "Use of unresolved identifier OnePasswordExtension" error

If I simply go to the pod file and remove `use_frameworks!` and `pod install` again, change the bridging header import to `#import "OnePasswordExtension.h"` the project will build fine.

I saw that #268 which was included with 1.6.3 was related to this.

**Comment by tapi** [comment]
2 questions.
- What version of Xcode?
- Does `@import OnePasswordExtension;` work when frameworks are enabled?

Xcode 7.1 uses a new version of clang which is way more strict about how things are imported. May be related to https://github.com/CocoaPods/CocoaPods/issues/4420#issuecomment-151674437

**Comment by obuseme** [comment]
Xcode 7.1 (7B91b)

Yes, that fixes it!  Should documentation be updated?  Would be nice to get some docs specific to using the Cocoapod.

**Comment by radazzouz** [comment]
@tapi thanks for the assist buddy!

@obuseme, I am really glad that you guys sorted it all out. 

In [our README](https://github.com/AgileBits/onepassword-app-extension#step-2-install-the-latest-versions-of-1password--xcode) we recommend installing the latest version of 1Password and of Xcode. May be CocoaPods ought to specify that version 0.39.0 requires Xcode 7.1 or later...

Anyway, since this is not an App Extension API-specific issue, I am closing this issue as `invalid`.

Cheers!
