### ISSUE TITLE
Move framework/carthage support to master branch

### ISSUE THREAD

**Issue by timonus** [AgileBits/onepassword-app-extension#285]
It doesn't make any sense to require people trying to use carthage to use a different dedicated branch, this should all be achievable on the master branch and in releases.

**Comment by radazzouz** [comment]
Hi @timonus,

Thanks for taking the time to write in :+1:

The main reason why Carthage (framework) support is not on master can be seen in [my comment](https://github.com/AgileBits/onepassword-app-extension/pull/151#issuecomment-68894681) in PR #151. You can also see the discussion from PR #152 for more details.

Since we can't support Carthage without the use of frameworks on master, I am labeling this issue as `wontfix` and closing it.

Please feel free to reopen it if you have a solution which does not involve forcing framework usage on master.

Best,
