### ISSUE TITLE
Filling Credit Card Details in Native View

### ISSUE THREAD

**Issue by robertherber** [AgileBits/onepassword-app-extension#286]
Hi guys,

Thanks for a great product! I'm working with a native app where we'd love to be able to offer our customers autofilling of credit card information though your extension. Is this possible or is it something you're planning on implementing?

Thanks,
Robert

**Comment by radazzouz** [comment]
Hi Robert,

Thanks for taking the time to file this issue and for your interest in filling Credit Cards into native apps.

At the moment, you can only fill credit card information into [web views](https://github.com/AgileBits/onepassword-app-extension#use-case-4-web-view-filling) using `fillItemIntoWebView:`.

It is in our plans to add the ability to fill credit card information into native apps in the future. Therefore, I am closing this issue since it duplicates #174 and add your vote to it. Please make sure that you watch #174 for updates.

Cheers!

Rad
