### ISSUE TITLE
Black Screen when Lock-On-Exit is not selected

### ISSUE THREAD

**Issue by valheru7** [AgileBits/onepassword-app-extension#326]
Using: 
v1.8.1 extension
v6.4 app

When 1password has Lock on Exit unselected in Security Settings, we are experiencing a repeatable issue on certain devices where the screen is completely black when we initiate the 1password extension from our own app. It seems to select the 1password extension and then the 1password drawer opens up and there's nothing but black. We have to force quit our own app to get out of itl.

These are our security settings:
![1passsettings](https://cloud.githubusercontent.com/assets/5475053/15331670/3ccf1834-1c17-11e6-980e-0696412a27cf.jpg)

On other devices, whether lock on exit is selected or not, it works just fine. 

We're using both:

`OnePasswordExtension.sharedExtension().findLoginForURLString`

and:

`OnePasswordExtension.sharedExtension().storeLoginForURLString`

I did a quick search and saw there was a black screen issue with a previous beta but nothing new. Any suggestions or other settings that may be causing this that we can verify?

**Comment by valheru7** [comment]
Possible workaround seems to be: Enabling a PIN Code. 

And the other device that does not repro the black screen is using Touch ID...but when disabling touch ID it still does not repro the black screen.

**Comment by radazzouz** [comment]
Hi @valheru7,

Thanks for taking the time to write in. I am really sorry to hear that you're experiencing this issue.

> Possible workaround seems to be: Enabling a PIN Code.

Yes, enabling either the PIN Code (or Touch ID if available) or "Lock On Exit" is indeed a workaround. This issue is only present in the extension if the Master Password is the unlock method **and** if `Settings > Security > Lock On Exit` is disabled.

Since this is a known bug in 1Password for iOS (OPI-3425) and not in the App Extension API, I am linking this issue to the internal issue and closing this one as `invalid`.

Best,
