### ISSUE TITLE
[WIP] Fix build errors and improve compatibility with iOS 10, Xcode 8, Swift 3.0 and Carthage

### ISSUE THREAD

**Issue by radazzouz** [agilebits/onepassword-app-extension#329]
See the [new/ios10](https://github.com/AgileBits/onepassword-app-extension/tree/new/ios10) branch.

**Comment by radazzouz** [comment]
For Carthage compatibility, please take a look at [`new/carthage+ios10`](https://github.com/AgileBits/onepassword-app-extension/tree/new/carthage%2Bios10) branch.

**Comment by lvandal** [comment]
Wow, that was quick. Thanks!

**Comment by radazzouz** [comment]
Thanks so much for the kind words, Luc! 😊

**Comment by lfarah** [comment]
Hey guys, I think now that Xcode is out we could merge the branch into master

**Comment by gks** [comment]
Hi @lfarah 

We're holding off on merging this branch because Swift 3.0 is not the default in Xcode 8. Currently Xcode 8 defaults to Swift 2.3 and the developer must specify they wish to use Swift 3.0. Until this becomes default we're probably going to keep this as a separate branch.

I don't have any information on how many developers are using Swift 3.0 vs Swift 2.3, but given I am not getting any questions about how to get it to work with Swift 3.0 makes me think that the number of developers using Swift 3 is minimal, or they're finding this thread easily enough. In either case I am fine with that and we're going to remain opinionated for simplification purposes. I don't want to make Swift 3 a requirement to use the extension since it's not the default. Once it becomes default we'll take another look at what is best for other developers.

I am sorry if this makes your life more difficult though. We do keep this branch up to date with master so that means you're getting the same changes here.

**Comment by lfarah** [comment]
Hey @gks, definitely makes sense!
I saw a lot of libraries that make the master with Swift 3 and have a 2.3 branch.
I agree 100% with your approach and your view on how Apple decided to make 2.3 as default right now.

**Comment by gks** [comment]
This was merged in as of the last release (1.8.5) so I'm closing this as complete.
