### ISSUE TITLE
1Password icon animation not smooth

### ISSUE THREAD

**Issue by Formationthing** [AgileBits/onepassword-app-extension#333]
1. Touch ID in 1Password iOS on
2. Open Safari iOS
3. Open Safari 1Password Extension
4. It comes Touch ID window
5. Tap the button **cancel**
6. You can see: 1Password icon animation is not smooth.
7. Tap Touch ID icon again.
8. Now comes issue again. 1Password icon animation is not smooth.

Please fix.

I test with iPad in landscape mode
iOS 9.3.2

**Comment by gks** [comment]
Hi @Formationthing 

Thanks for reporting this. I've filed a bug report in our internal system. This github project is only for our app extension API, which isn't related to what you're reporting this bug about. So I am therefore closing this as won't do since it's not applicable to this project.

Sorry for the trouble though!

**Comment by Formationthing** [comment]
@gks 
Ok. Can this be fixed?

**Comment by radazzouz** [comment]
Hi @Formationthing,

> Ok. Can this be fixed?

We are do not know at this stage. Issue #301 is similar to this one. We have filed an internal bug about it and we also filed a bug with Apple (rdar://24607728).

As my colleague, @gks, mentioned in his previous response, this is not an *App Extension API* issue. It is a 1Password issue. Thanks for understanding!

Cheers!
