### ISSUE TITLE
Feature Request: Option to create more logins from extension if a login already exists for a domain

### ISSUE THREAD

**Issue by papernapkinhead** [AgileBits/onepassword-app-extension#343]
Hi there! It appears that, currently (6.4.3), the only time a new login can be created from the extension is if a login does not already exist for a domain.

We are working on implementing 1Password support in a situation where users may already have an entry for a given domain and it would be helpful for them to generate a second entry from within the extension for that domain. Please consider adding support for this workflow.

Thanks!!
Steve

**Comment by radazzouz** [comment]
Hello Steve,

Thanks for taking the time to request this feature. 👍

>  a situation where users may already have an entry for a given domain and it would be helpful for them to generate a second entry from within the extension for that domain.

We have considered this feature in the past and we decided agaist it. And here is why:

Our goal is to facilitate Login for our mutual users. We want users to spend the least amount of time in the 1Password Extension. We want them to quickly login using it so that they can use your app instead.

In fact, the last thing we want is for users to "fiddle" in the extension instead of logging in ASAP. The whole purpose of `findLoginForURLString:` is to show all matching logins and allow the user to quickly fill her credentials. Adding the ability to create new Logins in `findLoginForURLString:` might upset some developers who will notice that their users are spending a lot of time in the extension rather than quickly login and use their app instead.

If users want to create a new Login the have the option to do so in the main app (while using 1Password and not your app) or if you, as a third party developer, add the `storeLoginForURLString:` capability.

That said, I am closing this issue as `won't do`. If you have any other questions or concerns, please do let me know.

Cheers!

**Comment by papernapkinhead** [comment]
Completely understandable—thanks for the explanation, @radazzouz ! Seems like `storeLoginForURLString:` will be the way to go for this secondary password (but sadly, it won't allow folks to use 1Password's strong password generator!)

**Comment by radazzouz** [comment]
Thanks for getting back to me, @papernapkinhead !

I am really glad to hear that you will opt for `storeLoginForURLString:` in your app.

I also wanted to point out that `storeLoginForURLString:` does allow users to use the password generator. And here's how to to it.

1. Tap on "Generate New Password" 
![](https://www.evernote.com/l/AVS5SHhzFfJG06P_i7l6uqziLUIpVy_LvG4B/image.png)

2. Tap on "Show Password Recipe" 
![](https://www.evernote.com/l/AVQb3tt2PSxK0IIFuGhkIWHHGV_eVsZsog8B/image.png)

3. Swipe left and right to toggle between the **Characters** and **Words** password generators.
![](https://www.evernote.com/l/AVT-Kb4gyyxNEL0gClyslr7YkrSbmKBETxAB/image.png)
![](https://www.evernote.com/l/AVQ9b3Y6-ElBrpNrz3YsKY1_D6PF9tXhUisB/image.png)

Hope that this helps!

All the Best,

**Comment by papernapkinhead** [comment]
Aha—that's fantastic! Thanks @radazzouz  👍
