### ISSUE TITLE
Assets should be included in framework

### ISSUE THREAD

**Issue by lvandal** [AgileBits/onepassword-app-extension#356]
Currently, you need to keep a copy of the .xcassets folder in order to include them manually into a project. It would be a better idea to include them into the framework.

**Comment by gks** [comment]
Hi @lvandal 

Master, which is the branch we most care about since it's the one most people will use doesn't use frameworks and everything is dragged into the project. I assume you're using our `add-framework-support` branch, is that correct?

This one is mostly community supported and while we do merge master into that branch in an attempt to keep that up to date as Pull Requests are merged in it isn't something I plan to do any real changes on. 

If you'd like to see this changed in the `add-framework-support` branch I'd love to invite you to create a pull request with the changes to it. After some testing and confirmation it works as it should (don't forget to update any of our sample projects!) I'm sure we could work on some arrangement to get that merged. 

I'm going to mark this issue as won't do and close it for the above reason that `master` is not using frameworks though.
