### ISSUE TITLE
Navigation Bar hidden behind in-call status bar

### ISSUE THREAD

**Issue by iCarambaa** [agilebits/onepassword-app-extension#390]
The navigation bar is hidden behind the in-call status bar (or personal hotspot bar).

![img_1559](https://user-images.githubusercontent.com/7224274/31382430-f1bd670e-adb7-11e7-9827-6f7767a14e70.jpeg)

**Comment by gks** [comment]
Hi @iCarambaa 

Thanks for reporting this. While definitely a relevant issue, it's not technically part of the app extension API and belongs in our internal bug tracker. So I've moved this bug report to that so that it'll get the attention it needs.  Technically that part of the app is part of the 1Password application, not the extension API here. 

Great find though!
