### ISSUE TITLE
Issues Launching Extension without Configuring 1Password

### ISSUE THREAD

**Issue by davidbollen** [agilebits/onepassword-app-extension#400]
Launching the 1Password extension before the user has logged into 1Password causes a white screen to appear which is unable to be dismissed. The `OnePasswordExtension.shared().isAppExtensionAvailable() ` function returns true even though the use has not authenticated with 1Password.

Steps to Reproduce:
1. Ensure 1Password is installed on the device but the user has not logged into 1Password.
2. Launch the application using this extension.

**Comment by gks** [comment]
Hi @davidbollen 

Sorry for the delay in responding here, it has been a busy week or so for me. I just tested this and was not able to duplicate it. Using the ACME demo apps present in the repository here I get what you see in the screenshot below.

Are you able to duplicate the same thing with the demo apps or does it not happen there for you like it is for me?

![simulator screen shot - iphone 8 plus - 2018-01-17 at 13 01 55](https://user-images.githubusercontent.com/366223/35058681-ba225102-fb86-11e7-87ee-b7126ce3d31c.png)

**Comment by davidbollen** [comment]
Hi @gks 

I am able to reproduce this issue in the sample project. I've narrowed down the issue, this only occurs when you have downloaded but haven't launch the 1Password app.

**Comment by gks** [comment]
@davidbollen I was able to duplicate. Thanks for the extra information there that helped me to to that point.

This is not an app extension issue specifically but instead is an issue that needs fixing in the main 1Password application. So I'm going to close this issue here but will create the necessary bug in our internal tracker so we can try to get this buttoned up for the next update.

Thank you again for reporting this one, it's not a pleasant issue for new users or users who may have reset their data in the app.
