### ISSUE TITLE
The 1p sheet moves behind the app after FaceID or TouchID authentication

### ISSUE THREAD

**Issue by sra** [agilebits/onepassword-app-extension#401]
After adding this extension to the app, hitting the button brings up the 1p as expected. If 1p is unlocked, the list shows and is filtered properly and selected entries work fine.

If it is locked, but you unlock with a password, it works as above.

If it is locked, but you unlock with TouchID or FaceID, the sheet seems to go behind the app. Pushing the button again simply complains that there is an attempt to present  UIActivityViewController which is already presenting.

Has anyone seen this before?

**Comment by gks** [comment]
Hi @sra 

I'm not aware of this happening. Any chance you could write in to our support email support+appext@agilebits.com and supply a screenshot or video that shows this? Ideally without any private information there. 

I ask to email in as if this is an issue it's not one that is caused by the app extension code but our internal 1Password code, so it's technically not an issue that belongs in this repository but our internal bug tracker. 

Thanks!
