### ISSUE TITLE
Best practices question - Should we auto-submit a login when user selects a password?

### ISSUE THREAD

**Issue by jgale** [agilebits/onepassword-app-extension#68]
I filed this on the forum but it was suggested I post it as a GitHub issue.
https://discussions.agilebits.com/discussion/27524/ios-extension-best-practice-q-should-we-automatically-submit-login#latest

I have a general purpose question on best practices.

I personally feel like when I launch the extension and pick an item from my vault, it should fill in this login/password field but also should immediately submit the login call to the server. Your sample code just fills the fields.

I guess I'm used to standard 1Password Cmd-\ behaviour where it fills the fields AND submits.

Any thoughts on this?

Thanks!

**Comment by smileyborg** [comment]
+1 to this question.

I have to disagree on the conclusion/recommendation here though. The user experience is unquestionably better without having to also tap a "Sign In" button after filling the fields. If 1Password **could** auto-submit web forms on iOS, I am certain that it would, because it's a better/simpler user experience. In fact, if you look at what the 1Password iOS app's built-in 1Browser does, it auto-submits the forms after filling them! This is obviously consistent with the Mac too.

So given that, I definitely think that since it **is** possible for native apps to auto-submit as well, they **should**. I don't think that this is confusing for users -- if anything, the inability to auto-submit in a web view/Safari is the issue.

Please reconsider this guidance, and address this question in the README/example apps.

**Comment by dgoldman-ebay** [comment]
:-1: to @smileyborg's thoughts.

**Comment by dgoldman-ebay** [comment]
Yikes! I meant to type :+1:, not :-1: !!!!!

**Comment by radazzouz** [comment]
Hey guys,

Right now 1Password will only fill and not submit into Mobile Safari. We are considering/evaluating the possibility to fill and submit internally.

Since my last comment on Aug 15, 2014, many 3rd party developers have integrated with 1Password and some of them filled, others filled and submitted the form.

We think that it's up to the developer to decide whether or not to submit after filling with the 1Password Extension.

Hope that this helps :smile: 

Cheers!

**Comment by dgoldman-ebay** [comment]
@radazzouz works for me! :smiley_cat:

**Comment by smileyborg** [comment]
@radazzouz Works for me too. Can you please add a short note to this effect in the README? Given that the sample code just fills (and does not submit), I'd wager that most developers will do exactly the same. Would definitely be better to make sure they understand the choice is theirs.

**Comment by radazzouz** [comment]
Hi @smileyborg,

As I mentioned in my previous reply, the only possible way to submit after filling is when using `@"org.appextension.find-login-action"`. It will not work in Mobile Safari or when filling into a web view. That's why there is no official recommendation at this moment.

Best,

**Comment by smileyborg** [comment]
I think you misunderstood me, I am simply suggesting that you make a note that it is up to the developer in the README. The current sample code suggests that devs should not auto-submit, and since there is no guidance on the README (and most people will not dig through the Closed Issues to find this one), it is ambiguous.

**Comment by radazzouz** [comment]
Hi @smileyborg,

Thank you for the followup!

There is no official recommendation at this moment. This means that developers can choose whether or not they want to auto submit or not. It also means that no official statement should be made in the README about it yet.

Thanks!
